export type LayoutType = {
  style?: any,
  column?: boolean,
  rowReverse?: boolean,
  columnReverse?: boolean,
  justifyContent?: 'start' | 'flex-start' | 'center' | 'end' | 'flex-end' | 'spaced' | 'space-between' | 'around' | 'space-around' | 'space-evenly';
  alignItems?: 'start' | 'center' | 'end' | 'stretch' | 'baseline',
  alignSelf?: 'start' | 'center' | 'end' | 'stretch' | 'baseline',
  alignContent?: 'start' | 'flex-start' | 'center' | 'end' | 'flex-end' | 'spaced' | 'space-between' | 'around' | 'space-around' | 'stretch',
  wrap?: boolean,
  wrapReverse?: boolean,
  flexGrow?: number,
  flexShrink?: number,
  flexBasis?: string,
  flex?: string,
  width?: string,
  height?: string,
  breakpoints?: any,
  element?: 'article' | 'aside' | 'div' | 'figure' | 'footer' | 'form' | 'header' | 'main' | 'nav' | 'section',
  componentRef?: any,
  className?: string,
  children: React.ReactNode,
}

export type RowType = {
  style?: React.CSSProperties,
  reverse?: boolean,
  vertical?: 'start' | 'center' | 'end' | 'stretch' | 'baseline',
  horizontal?: 'start' | 'flex-start' | 'center' | 'end' | 'flex-end' | 'spaced' | 'space-between' | 'around' | 'space-around' | 'space-evenly',
  justifyContent?: 'start' | 'flex-start' | 'center' | 'end' | 'flex-end' | 'spaced' | 'space-between' | 'around' | 'space-around' | 'space-evenly',
  alignItems?: 'start' | 'center' | 'end' | 'stretch' | 'baseline',
  alignSelf?: 'start' | 'center' | 'end' | 'stretch' | 'baseline',
  alignContent?: 'start' | 'flex-start' | 'center' | 'end' | 'flex-end' | 'spaced' | 'space-between' | 'around' | 'space-around' | 'stretch',
  wrap?: boolean,
  wrapReverse?: boolean,
  flex?: string,
  width?: string,
  height?: string,
  flexGrow?: number,
  flexShrink?: number,
  flexBasis?: string,
  breakpoints?: object,
  element?: 'article' | 'aside' | 'div' | 'figure' | 'footer' | 'form' | 'header' | 'main' | 'nav' | 'section',
  className?: string,
  children: React.ReactNode
}

export type ColumnType = {
  style?: React.CSSProperties,
  reverse?: boolean,
  horizontal?: 'center' | 'start' | 'end' | 'stretch' | 'baseline',
  vertical?: 'start' | 'flex-start' | 'center' | 'end' | 'flex-end' | 'spaced' | 'space-between' | 'around' | 'space-around' | 'space-evenly',
  justifyContent?: 'start' | 'flex-start' | 'center' | 'end' | 'flex-end' | 'spaced' | 'space-between' | 'around' | 'space-around' | 'space-evenly',
  alignItems?: 'start' | 'center' | 'end' | 'stretch' | 'baseline',
  alignSelf?: 'start' | 'center' | 'end' | 'stretch' | 'baseline',
  alignContent?: 'start' | 'flex-start' | 'center' | 'end' | 'flex-end' | 'spaced' | 'space-between' | 'around' | 'space-around' | 'stretch',
  wrap?: boolean,
  wrapReverse?: boolean,
  flex?: string,
  width?: string,
  height?: string,
  flexGrow?: number,
  flexShrink?: number,
  flexBasis?: string,
  breakpoints?: object,
  element?: 'article' | 'aside' | 'div' | 'figure' | 'footer' | 'form' | 'header' | 'main' | 'nav' | 'section',
  className?: string,
  children: React.ReactNode
}
